name: service-metrics
code: service
description: 'service metrics collectors promql'
cronExpression: '@every 1m'
promQls:
  - name: 'pod number'
    code: 'PodNumber'
    query: 'sum(max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)'
  - name: 'cpu request'
    code: 'CPURequest'
    query: 'avg(sum(max_over_time(kube_pod_container_resource_requests_cpu_cores{namespace!=""} [1h]) * on (namespace,pod)  group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (pod,workload)) by (workload)'
  - name: 'cpu limit'
    code: 'CPULimit'
    query: 'avg(sum(max_over_time(kube_pod_container_resource_limits_cpu_cores{namespace!=""} [1h]) * on (namespace,pod)  group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (pod,workload)) by (workload)'
  - name: 'memory request'
    code: 'MemoryRequest'
    query: 'avg(sum(max_over_time(kube_pod_container_resource_requests_memory_bytes{namespace!=""} [1h])/1024/1024/1024 * on (namespace,pod)  group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (pod,workload)) by (workload)'
  - name: 'memory limit'
    code: 'MemoryLimit'
    query: 'avg(sum(max_over_time(kube_pod_container_resource_limits_memory_bytes{namespace!=""} [1h])/1024/1024/1024 * on (namespace,pod)  group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (pod,workload)) by (workload)'
  - name: 'cpu usage max'
    code: 'CPUUsageMax'
    query: 'sum(sum(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=!""} [1h])) by (pod) *  on (pod) group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)'
  - name: 'cpu usage average'
    code: 'CPUUsageAvg'
    query: 'sum(sum(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace!=""} [1h])) by (pod) *  on (pod) group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)'
  - name: 'cpu usage min'
    code: 'CPUUsageMin'
    query: 'sum(sum(min_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace!=""} [1h])) by (pod) *  on (pod) group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)'
  - name: 'memory usage max'
    code: 'MemoryUsageMax'
    query: 'sum(max_over_time(container_memory_working_set_bytes{ namespace="openshift-monitoring", container!="", image!=""} [1h])  * on(namespace,pod)    group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)/1024/1024/1024'
  - name: 'memory usage average'
    code: 'MemoryUsageAvg'
    query: 'sum(avg_over_time(container_memory_working_set_bytes{ namespace="openshift-monitoring", container!="", image!=""} [1h])  * on(namespace,pod)    group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)/1024/1024/1024'
  - name: 'memory usage min'
    code: 'MemoryUsageMin'
    query: 'sum(min_over_time(container_memory_working_set_bytes{ namespace="openshift-monitoring", container!="", image!=""} [1h])  * on(namespace,pod)    group_left(workload, workload_type) max_over_time(namespace_workload_pod:kube_pod_owner:relabel [1h])) by (workload)/1024/1024/1024'